# Generated by Django 5.2.6 on 2025-09-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
    ]
