# Generated by Django 5.2.6 on 2025-09-20 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_created_at_shortcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcard',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='shortcard',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shortcard',
            name='badge',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='shortcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcard',
            name='locale',
            field=models.CharField(default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='shortcard',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='shortcard',
            name='section',
            field=models.CharField(default='home', max_length=50),
        ),
        migrations.AddField(
            model_name='shortcard',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='shortcard',
            index=models.Index(fields=['active', 'section', 'locale', 'order'], name='content_sho_active_0c2ec0_idx'),
        ),
    ]
