# Generated by Django 5.2.6 on 2025-09-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('CITY', 'City'), ('LANDMARK', 'Landmark'), ('PROPERTY', 'Property')], max_length=20)),
                ('display', models.CharField(max_length=200)),
                ('ref_id', models.PositiveIntegerField()),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
