# Generated by Django 5.2.6 on 2025-09-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightlyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_date', models.DateField()),
                ('allotment', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='property.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.roomtype')),
            ],
            options={
                'unique_together': {('property', 'room_type', 'stay_date')},
            },
        ),
        migrations.CreateModel(
            name='NightlyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_date', models.DateField()),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='property.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.roomtype')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'stay_date'], name='inventory_n_propert_bca9d2_idx'), models.Index(fields=['currency'], name='inventory_n_currenc_ebcfb3_idx')],
                'unique_together': {('property', 'room_type', 'rate_plan', 'stay_date', 'currency')},
            },
        ),
    ]
