# Generated by Django 5.2.6 on 2025-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['placement', 'order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='featuredcollection',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_at', 'id']},
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['placement', 'active'], name='marketing_b_placeme_579797_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_at', 'end_at'], name='marketing_p_start_a_10d331_idx'),
        ),
    ]
